//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Tamas Ionut\Documents\Visual Studio 2015\Projects\ConsoleApplication10\ConsoleApplication10\CLanguage.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Prometheus.Services.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CLanguageParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface ICLanguageListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] CLanguageParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] CLanguageParser.PrimaryExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.genericSelection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericSelection([NotNull] CLanguageParser.GenericSelectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.genericSelection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericSelection([NotNull] CLanguageParser.GenericSelectionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.genericAssocList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericAssocList([NotNull] CLanguageParser.GenericAssocListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.genericAssocList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericAssocList([NotNull] CLanguageParser.GenericAssocListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.genericAssociation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericAssociation([NotNull] CLanguageParser.GenericAssociationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.genericAssociation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericAssociation([NotNull] CLanguageParser.GenericAssociationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] CLanguageParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] CLanguageParser.PostfixExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.argumentExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentExpressionList([NotNull] CLanguageParser.ArgumentExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.argumentExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentExpressionList([NotNull] CLanguageParser.ArgumentExpressionListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CLanguageParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CLanguageParser.UnaryExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] CLanguageParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] CLanguageParser.UnaryOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] CLanguageParser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] CLanguageParser.CastExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] CLanguageParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] CLanguageParser.MultiplicativeExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] CLanguageParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] CLanguageParser.AdditiveExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpression([NotNull] CLanguageParser.ShiftExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpression([NotNull] CLanguageParser.ShiftExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] CLanguageParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] CLanguageParser.RelationalExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] CLanguageParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] CLanguageParser.EqualityExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] CLanguageParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] CLanguageParser.AndExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusiveOrExpression([NotNull] CLanguageParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusiveOrExpression([NotNull] CLanguageParser.ExclusiveOrExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusiveOrExpression([NotNull] CLanguageParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusiveOrExpression([NotNull] CLanguageParser.InclusiveOrExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CLanguageParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CLanguageParser.LogicalAndExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CLanguageParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CLanguageParser.LogicalOrExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] CLanguageParser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] CLanguageParser.ConditionalExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] CLanguageParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] CLanguageParser.AssignmentExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] CLanguageParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] CLanguageParser.AssignmentOperatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CLanguageParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CLanguageParser.ExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] CLanguageParser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] CLanguageParser.ConstantExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] CLanguageParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] CLanguageParser.DeclarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifiers([NotNull] CLanguageParser.DeclarationSpecifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifiers([NotNull] CLanguageParser.DeclarationSpecifiersContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifiers2([NotNull] CLanguageParser.DeclarationSpecifiers2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifiers2([NotNull] CLanguageParser.DeclarationSpecifiers2Context context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationSpecifier([NotNull] CLanguageParser.DeclarationSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationSpecifier([NotNull] CLanguageParser.DeclarationSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclaratorList([NotNull] CLanguageParser.InitDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclaratorList([NotNull] CLanguageParser.InitDeclaratorListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclarator([NotNull] CLanguageParser.InitDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclarator([NotNull] CLanguageParser.InitDeclaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorageClassSpecifier([NotNull] CLanguageParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorageClassSpecifier([NotNull] CLanguageParser.StorageClassSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] CLanguageParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] CLanguageParser.TypeSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structOrUnionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructOrUnionSpecifier([NotNull] CLanguageParser.StructOrUnionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structOrUnionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructOrUnionSpecifier([NotNull] CLanguageParser.StructOrUnionSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structOrUnion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructOrUnion([NotNull] CLanguageParser.StructOrUnionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structOrUnion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructOrUnion([NotNull] CLanguageParser.StructOrUnionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclarationList([NotNull] CLanguageParser.StructDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclarationList([NotNull] CLanguageParser.StructDeclarationListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaration([NotNull] CLanguageParser.StructDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaration([NotNull] CLanguageParser.StructDeclarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.specifierQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecifierQualifierList([NotNull] CLanguageParser.SpecifierQualifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.specifierQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecifierQualifierList([NotNull] CLanguageParser.SpecifierQualifierListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclaratorList([NotNull] CLanguageParser.StructDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclaratorList([NotNull] CLanguageParser.StructDeclaratorListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDeclarator([NotNull] CLanguageParser.StructDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDeclarator([NotNull] CLanguageParser.StructDeclaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumSpecifier([NotNull] CLanguageParser.EnumSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumSpecifier([NotNull] CLanguageParser.EnumSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumeratorList([NotNull] CLanguageParser.EnumeratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumeratorList([NotNull] CLanguageParser.EnumeratorListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerator([NotNull] CLanguageParser.EnumeratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerator([NotNull] CLanguageParser.EnumeratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumerationConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationConstant([NotNull] CLanguageParser.EnumerationConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumerationConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationConstant([NotNull] CLanguageParser.EnumerationConstantContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.atomicTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicTypeSpecifier([NotNull] CLanguageParser.AtomicTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.atomicTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicTypeSpecifier([NotNull] CLanguageParser.AtomicTypeSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeQualifier([NotNull] CLanguageParser.TypeQualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeQualifier([NotNull] CLanguageParser.TypeQualifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSpecifier([NotNull] CLanguageParser.FunctionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSpecifier([NotNull] CLanguageParser.FunctionSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.alignmentSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlignmentSpecifier([NotNull] CLanguageParser.AlignmentSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.alignmentSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlignmentSpecifier([NotNull] CLanguageParser.AlignmentSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] CLanguageParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] CLanguageParser.DeclaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.directDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectDeclarator([NotNull] CLanguageParser.DirectDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.directDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectDeclarator([NotNull] CLanguageParser.DirectDeclaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccDeclaratorExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccDeclaratorExtension([NotNull] CLanguageParser.GccDeclaratorExtensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccDeclaratorExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccDeclaratorExtension([NotNull] CLanguageParser.GccDeclaratorExtensionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccAttributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccAttributeSpecifier([NotNull] CLanguageParser.GccAttributeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccAttributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccAttributeSpecifier([NotNull] CLanguageParser.GccAttributeSpecifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccAttributeList([NotNull] CLanguageParser.GccAttributeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccAttributeList([NotNull] CLanguageParser.GccAttributeListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGccAttribute([NotNull] CLanguageParser.GccAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGccAttribute([NotNull] CLanguageParser.GccAttributeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.nestedParenthesesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedParenthesesBlock([NotNull] CLanguageParser.NestedParenthesesBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.nestedParenthesesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedParenthesesBlock([NotNull] CLanguageParser.NestedParenthesesBlockContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer([NotNull] CLanguageParser.PointerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer([NotNull] CLanguageParser.PointerContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeQualifierList([NotNull] CLanguageParser.TypeQualifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeQualifierList([NotNull] CLanguageParser.TypeQualifierListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.parameterTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterTypeList([NotNull] CLanguageParser.ParameterTypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.parameterTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterTypeList([NotNull] CLanguageParser.ParameterTypeListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] CLanguageParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] CLanguageParser.ParameterListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclaration([NotNull] CLanguageParser.ParameterDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclaration([NotNull] CLanguageParser.ParameterDeclarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] CLanguageParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] CLanguageParser.IdentifierListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] CLanguageParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] CLanguageParser.TypeNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstractDeclarator([NotNull] CLanguageParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstractDeclarator([NotNull] CLanguageParser.AbstractDeclaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.directAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectAbstractDeclarator([NotNull] CLanguageParser.DirectAbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.directAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectAbstractDeclarator([NotNull] CLanguageParser.DirectAbstractDeclaratorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedefName([NotNull] CLanguageParser.TypedefNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedefName([NotNull] CLanguageParser.TypedefNameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] CLanguageParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] CLanguageParser.InitializerContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerList([NotNull] CLanguageParser.InitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerList([NotNull] CLanguageParser.InitializerListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.designation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignation([NotNull] CLanguageParser.DesignationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.designation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignation([NotNull] CLanguageParser.DesignationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.designatorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignatorList([NotNull] CLanguageParser.DesignatorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.designatorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignatorList([NotNull] CLanguageParser.DesignatorListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDesignator([NotNull] CLanguageParser.DesignatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDesignator([NotNull] CLanguageParser.DesignatorContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticAssertDeclaration([NotNull] CLanguageParser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticAssertDeclaration([NotNull] CLanguageParser.StaticAssertDeclarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CLanguageParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CLanguageParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatement([NotNull] CLanguageParser.LabeledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatement([NotNull] CLanguageParser.LabeledStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStatement([NotNull] CLanguageParser.CompoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStatement([NotNull] CLanguageParser.CompoundStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.blockItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockItemList([NotNull] CLanguageParser.BlockItemListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.blockItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockItemList([NotNull] CLanguageParser.BlockItemListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockItem([NotNull] CLanguageParser.BlockItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockItem([NotNull] CLanguageParser.BlockItemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] CLanguageParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] CLanguageParser.ExpressionStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionStatement([NotNull] CLanguageParser.SelectionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionStatement([NotNull] CLanguageParser.SelectionStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIterationStatement([NotNull] CLanguageParser.IterationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIterationStatement([NotNull] CLanguageParser.IterationStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] CLanguageParser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] CLanguageParser.JumpStatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] CLanguageParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] CLanguageParser.CompilationUnitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslationUnit([NotNull] CLanguageParser.TranslationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslationUnit([NotNull] CLanguageParser.TranslationUnitContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.externalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternalDeclaration([NotNull] CLanguageParser.ExternalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.externalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternalDeclaration([NotNull] CLanguageParser.ExternalDeclarationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] CLanguageParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] CLanguageParser.FunctionDefinitionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationList([NotNull] CLanguageParser.DeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationList([NotNull] CLanguageParser.DeclarationListContext context);
}
} // namespace ConsoleApplication10
