//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Tamas Ionut\Documents\Visual Studio 2015\Projects\ConsoleApplication10\ConsoleApplication10\CLanguage.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Prometheus.Services.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICLanguageListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class CLanguageBaseListener : ICLanguageListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] CLanguageParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] CLanguageParser.PrimaryExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.genericSelection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericSelection([NotNull] CLanguageParser.GenericSelectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.genericSelection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericSelection([NotNull] CLanguageParser.GenericSelectionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.genericAssocList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericAssocList([NotNull] CLanguageParser.GenericAssocListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.genericAssocList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericAssocList([NotNull] CLanguageParser.GenericAssocListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.genericAssociation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericAssociation([NotNull] CLanguageParser.GenericAssociationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.genericAssociation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericAssociation([NotNull] CLanguageParser.GenericAssociationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfixExpression([NotNull] CLanguageParser.PostfixExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.postfixExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfixExpression([NotNull] CLanguageParser.PostfixExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.argumentExpressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentExpressionList([NotNull] CLanguageParser.ArgumentExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.argumentExpressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentExpressionList([NotNull] CLanguageParser.ArgumentExpressionListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] CLanguageParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] CLanguageParser.UnaryExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOperator([NotNull] CLanguageParser.UnaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOperator([NotNull] CLanguageParser.UnaryOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.castExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpression([NotNull] CLanguageParser.CastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.castExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpression([NotNull] CLanguageParser.CastExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] CLanguageParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] CLanguageParser.MultiplicativeExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] CLanguageParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] CLanguageParser.AdditiveExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.shiftExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShiftExpression([NotNull] CLanguageParser.ShiftExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.shiftExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShiftExpression([NotNull] CLanguageParser.ShiftExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] CLanguageParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] CLanguageParser.RelationalExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] CLanguageParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] CLanguageParser.EqualityExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpression([NotNull] CLanguageParser.AndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpression([NotNull] CLanguageParser.AndExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.exclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExclusiveOrExpression([NotNull] CLanguageParser.ExclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.exclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExclusiveOrExpression([NotNull] CLanguageParser.ExclusiveOrExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.inclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclusiveOrExpression([NotNull] CLanguageParser.InclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.inclusiveOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclusiveOrExpression([NotNull] CLanguageParser.InclusiveOrExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpression([NotNull] CLanguageParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpression([NotNull] CLanguageParser.LogicalAndExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpression([NotNull] CLanguageParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpression([NotNull] CLanguageParser.LogicalOrExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalExpression([NotNull] CLanguageParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalExpression([NotNull] CLanguageParser.ConditionalExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] CLanguageParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] CLanguageParser.AssignmentExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentOperator([NotNull] CLanguageParser.AssignmentOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.assignmentOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentOperator([NotNull] CLanguageParser.AssignmentOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CLanguageParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CLanguageParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantExpression([NotNull] CLanguageParser.ConstantExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.constantExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantExpression([NotNull] CLanguageParser.ConstantExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] CLanguageParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] CLanguageParser.DeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationSpecifiers([NotNull] CLanguageParser.DeclarationSpecifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationSpecifiers([NotNull] CLanguageParser.DeclarationSpecifiersContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationSpecifiers2([NotNull] CLanguageParser.DeclarationSpecifiers2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationSpecifiers2([NotNull] CLanguageParser.DeclarationSpecifiers2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationSpecifier([NotNull] CLanguageParser.DeclarationSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationSpecifier([NotNull] CLanguageParser.DeclarationSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclaratorList([NotNull] CLanguageParser.InitDeclaratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclaratorList([NotNull] CLanguageParser.InitDeclaratorListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitDeclarator([NotNull] CLanguageParser.InitDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitDeclarator([NotNull] CLanguageParser.InitDeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.storageClassSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorageClassSpecifier([NotNull] CLanguageParser.StorageClassSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.storageClassSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorageClassSpecifier([NotNull] CLanguageParser.StorageClassSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSpecifier([NotNull] CLanguageParser.TypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSpecifier([NotNull] CLanguageParser.TypeSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structOrUnionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructOrUnionSpecifier([NotNull] CLanguageParser.StructOrUnionSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structOrUnionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructOrUnionSpecifier([NotNull] CLanguageParser.StructOrUnionSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structOrUnion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructOrUnion([NotNull] CLanguageParser.StructOrUnionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structOrUnion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructOrUnion([NotNull] CLanguageParser.StructOrUnionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclarationList([NotNull] CLanguageParser.StructDeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclarationList([NotNull] CLanguageParser.StructDeclarationListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaration([NotNull] CLanguageParser.StructDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaration([NotNull] CLanguageParser.StructDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.specifierQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecifierQualifierList([NotNull] CLanguageParser.SpecifierQualifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.specifierQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecifierQualifierList([NotNull] CLanguageParser.SpecifierQualifierListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaratorList([NotNull] CLanguageParser.StructDeclaratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclaratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaratorList([NotNull] CLanguageParser.StructDeclaratorListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.structDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclarator([NotNull] CLanguageParser.StructDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.structDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclarator([NotNull] CLanguageParser.StructDeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumSpecifier([NotNull] CLanguageParser.EnumSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumSpecifier([NotNull] CLanguageParser.EnumSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumeratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumeratorList([NotNull] CLanguageParser.EnumeratorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumeratorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumeratorList([NotNull] CLanguageParser.EnumeratorListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumerator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerator([NotNull] CLanguageParser.EnumeratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumerator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerator([NotNull] CLanguageParser.EnumeratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.enumerationConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumerationConstant([NotNull] CLanguageParser.EnumerationConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.enumerationConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumerationConstant([NotNull] CLanguageParser.EnumerationConstantContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.atomicTypeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicTypeSpecifier([NotNull] CLanguageParser.AtomicTypeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.atomicTypeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicTypeSpecifier([NotNull] CLanguageParser.AtomicTypeSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeQualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeQualifier([NotNull] CLanguageParser.TypeQualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeQualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeQualifier([NotNull] CLanguageParser.TypeQualifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.functionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSpecifier([NotNull] CLanguageParser.FunctionSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.functionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSpecifier([NotNull] CLanguageParser.FunctionSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.alignmentSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlignmentSpecifier([NotNull] CLanguageParser.AlignmentSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.alignmentSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlignmentSpecifier([NotNull] CLanguageParser.AlignmentSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarator([NotNull] CLanguageParser.DeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarator([NotNull] CLanguageParser.DeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.directDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectDeclarator([NotNull] CLanguageParser.DirectDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.directDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectDeclarator([NotNull] CLanguageParser.DirectDeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccDeclaratorExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccDeclaratorExtension([NotNull] CLanguageParser.GccDeclaratorExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccDeclaratorExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccDeclaratorExtension([NotNull] CLanguageParser.GccDeclaratorExtensionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccAttributeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccAttributeSpecifier([NotNull] CLanguageParser.GccAttributeSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccAttributeSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccAttributeSpecifier([NotNull] CLanguageParser.GccAttributeSpecifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccAttributeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccAttributeList([NotNull] CLanguageParser.GccAttributeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccAttributeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccAttributeList([NotNull] CLanguageParser.GccAttributeListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.gccAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGccAttribute([NotNull] CLanguageParser.GccAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.gccAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGccAttribute([NotNull] CLanguageParser.GccAttributeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.nestedParenthesesBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedParenthesesBlock([NotNull] CLanguageParser.NestedParenthesesBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.nestedParenthesesBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedParenthesesBlock([NotNull] CLanguageParser.NestedParenthesesBlockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer([NotNull] CLanguageParser.PointerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.pointer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer([NotNull] CLanguageParser.PointerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeQualifierList([NotNull] CLanguageParser.TypeQualifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeQualifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeQualifierList([NotNull] CLanguageParser.TypeQualifierListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.parameterTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterTypeList([NotNull] CLanguageParser.ParameterTypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.parameterTypeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterTypeList([NotNull] CLanguageParser.ParameterTypeListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] CLanguageParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] CLanguageParser.ParameterListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDeclaration([NotNull] CLanguageParser.ParameterDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDeclaration([NotNull] CLanguageParser.ParameterDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] CLanguageParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] CLanguageParser.IdentifierListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] CLanguageParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] CLanguageParser.TypeNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.abstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAbstractDeclarator([NotNull] CLanguageParser.AbstractDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.abstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAbstractDeclarator([NotNull] CLanguageParser.AbstractDeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.directAbstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectAbstractDeclarator([NotNull] CLanguageParser.DirectAbstractDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.directAbstractDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectAbstractDeclarator([NotNull] CLanguageParser.DirectAbstractDeclaratorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.typedefName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedefName([NotNull] CLanguageParser.TypedefNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.typedefName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedefName([NotNull] CLanguageParser.TypedefNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer([NotNull] CLanguageParser.InitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer([NotNull] CLanguageParser.InitializerContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializerList([NotNull] CLanguageParser.InitializerListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.initializerList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializerList([NotNull] CLanguageParser.InitializerListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.designation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignation([NotNull] CLanguageParser.DesignationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.designation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignation([NotNull] CLanguageParser.DesignationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.designatorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignatorList([NotNull] CLanguageParser.DesignatorListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.designatorList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignatorList([NotNull] CLanguageParser.DesignatorListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDesignator([NotNull] CLanguageParser.DesignatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.designator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDesignator([NotNull] CLanguageParser.DesignatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.staticAssertDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStaticAssertDeclaration([NotNull] CLanguageParser.StaticAssertDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.staticAssertDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStaticAssertDeclaration([NotNull] CLanguageParser.StaticAssertDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CLanguageParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CLanguageParser.StatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.labeledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabeledStatement([NotNull] CLanguageParser.LabeledStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.labeledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabeledStatement([NotNull] CLanguageParser.LabeledStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompoundStatement([NotNull] CLanguageParser.CompoundStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.compoundStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompoundStatement([NotNull] CLanguageParser.CompoundStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.blockItemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockItemList([NotNull] CLanguageParser.BlockItemListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.blockItemList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockItemList([NotNull] CLanguageParser.BlockItemListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockItem([NotNull] CLanguageParser.BlockItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.blockItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockItem([NotNull] CLanguageParser.BlockItemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] CLanguageParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] CLanguageParser.ExpressionStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.selectionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectionStatement([NotNull] CLanguageParser.SelectionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.selectionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectionStatement([NotNull] CLanguageParser.SelectionStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterationStatement([NotNull] CLanguageParser.IterationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.iterationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterationStatement([NotNull] CLanguageParser.IterationStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpStatement([NotNull] CLanguageParser.JumpStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpStatement([NotNull] CLanguageParser.JumpStatementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompilationUnit([NotNull] CLanguageParser.CompilationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.compilationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompilationUnit([NotNull] CLanguageParser.CompilationUnitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.translationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTranslationUnit([NotNull] CLanguageParser.TranslationUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.translationUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTranslationUnit([NotNull] CLanguageParser.TranslationUnitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.externalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalDeclaration([NotNull] CLanguageParser.ExternalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.externalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalDeclaration([NotNull] CLanguageParser.ExternalDeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDefinition([NotNull] CLanguageParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDefinition([NotNull] CLanguageParser.FunctionDefinitionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CLanguageParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationList([NotNull] CLanguageParser.DeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CLanguageParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationList([NotNull] CLanguageParser.DeclarationListContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ConsoleApplication10
