//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Tamas Ionut\Documents\Visual Studio 2015\Projects\ConsoleApplication10\ConsoleApplication10\CLanguage.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Prometheus.Services.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CLanguageParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface ICLanguageVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] CLanguageParser.PrimaryExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.genericSelection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericSelection([NotNull] CLanguageParser.GenericSelectionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.genericAssocList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericAssocList([NotNull] CLanguageParser.GenericAssocListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.genericAssociation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenericAssociation([NotNull] CLanguageParser.GenericAssociationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] CLanguageParser.PostfixExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.argumentExpressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentExpressionList([NotNull] CLanguageParser.ArgumentExpressionListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] CLanguageParser.UnaryExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] CLanguageParser.UnaryOperatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpression([NotNull] CLanguageParser.CastExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] CLanguageParser.MultiplicativeExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] CLanguageParser.AdditiveExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpression([NotNull] CLanguageParser.ShiftExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] CLanguageParser.RelationalExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] CLanguageParser.EqualityExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] CLanguageParser.AndExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] CLanguageParser.ExclusiveOrExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] CLanguageParser.InclusiveOrExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpression([NotNull] CLanguageParser.LogicalAndExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpression([NotNull] CLanguageParser.LogicalOrExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] CLanguageParser.ConditionalExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] CLanguageParser.AssignmentExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] CLanguageParser.AssignmentOperatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CLanguageParser.ExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpression([NotNull] CLanguageParser.ConstantExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CLanguageParser.DeclarationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationSpecifiers([NotNull] CLanguageParser.DeclarationSpecifiersContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.declarationSpecifiers2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationSpecifiers2([NotNull] CLanguageParser.DeclarationSpecifiers2Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.declarationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationSpecifier([NotNull] CLanguageParser.DeclarationSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclaratorList([NotNull] CLanguageParser.InitDeclaratorListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclarator([NotNull] CLanguageParser.InitDeclaratorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorageClassSpecifier([NotNull] CLanguageParser.StorageClassSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifier([NotNull] CLanguageParser.TypeSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.structOrUnionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructOrUnionSpecifier([NotNull] CLanguageParser.StructOrUnionSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.structOrUnion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructOrUnion([NotNull] CLanguageParser.StructOrUnionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.structDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclarationList([NotNull] CLanguageParser.StructDeclarationListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaration([NotNull] CLanguageParser.StructDeclarationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.specifierQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecifierQualifierList([NotNull] CLanguageParser.SpecifierQualifierListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.structDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaratorList([NotNull] CLanguageParser.StructDeclaratorListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.structDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclarator([NotNull] CLanguageParser.StructDeclaratorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumSpecifier([NotNull] CLanguageParser.EnumSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeratorList([NotNull] CLanguageParser.EnumeratorListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator([NotNull] CLanguageParser.EnumeratorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.enumerationConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationConstant([NotNull] CLanguageParser.EnumerationConstantContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.atomicTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicTypeSpecifier([NotNull] CLanguageParser.AtomicTypeSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.typeQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeQualifier([NotNull] CLanguageParser.TypeQualifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSpecifier([NotNull] CLanguageParser.FunctionSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.alignmentSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignmentSpecifier([NotNull] CLanguageParser.AlignmentSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarator([NotNull] CLanguageParser.DeclaratorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.directDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectDeclarator([NotNull] CLanguageParser.DirectDeclaratorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.gccDeclaratorExtension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGccDeclaratorExtension([NotNull] CLanguageParser.GccDeclaratorExtensionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.gccAttributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGccAttributeSpecifier([NotNull] CLanguageParser.GccAttributeSpecifierContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.gccAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGccAttributeList([NotNull] CLanguageParser.GccAttributeListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.gccAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGccAttribute([NotNull] CLanguageParser.GccAttributeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.nestedParenthesesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedParenthesesBlock([NotNull] CLanguageParser.NestedParenthesesBlockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.pointer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointer([NotNull] CLanguageParser.PointerContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.typeQualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeQualifierList([NotNull] CLanguageParser.TypeQualifierListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.parameterTypeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterTypeList([NotNull] CLanguageParser.ParameterTypeListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] CLanguageParser.ParameterListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclaration([NotNull] CLanguageParser.ParameterDeclarationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierList([NotNull] CLanguageParser.IdentifierListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] CLanguageParser.TypeNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractDeclarator([NotNull] CLanguageParser.AbstractDeclaratorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.directAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirectAbstractDeclarator([NotNull] CLanguageParser.DirectAbstractDeclaratorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedefName([NotNull] CLanguageParser.TypedefNameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] CLanguageParser.InitializerContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerList([NotNull] CLanguageParser.InitializerListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.designation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesignation([NotNull] CLanguageParser.DesignationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.designatorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesignatorList([NotNull] CLanguageParser.DesignatorListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesignator([NotNull] CLanguageParser.DesignatorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticAssertDeclaration([NotNull] CLanguageParser.StaticAssertDeclarationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CLanguageParser.StatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledStatement([NotNull] CLanguageParser.LabeledStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundStatement([NotNull] CLanguageParser.CompoundStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.blockItemList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockItemList([NotNull] CLanguageParser.BlockItemListContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockItem([NotNull] CLanguageParser.BlockItemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] CLanguageParser.ExpressionStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectionStatement([NotNull] CLanguageParser.SelectionStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterationStatement([NotNull] CLanguageParser.IterationStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] CLanguageParser.JumpStatementContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilationUnit([NotNull] CLanguageParser.CompilationUnitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslationUnit([NotNull] CLanguageParser.TranslationUnitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.externalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternalDeclaration([NotNull] CLanguageParser.ExternalDeclarationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDefinition([NotNull] CLanguageParser.FunctionDefinitionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CLanguageParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationList([NotNull] CLanguageParser.DeclarationListContext context);
}
} // namespace ConsoleApplication10
